### ISSUE TITLE
watch change does not work

### ISSUE THREAD

**Issue by aetna-softwares** [tettusud/merge-jsons-webpack-plugin#21]
I checked the other ticket (especially #11) but can't get it working on my project.

To eliminate possibilities of misusage on my project, I test as following : 
- clone your repo
- run npm install in main directory
- go in example directory and run npm install
- change the package.json to add --watch-content-base to the start script
- run npm run start
- modify the json, it does not compile automatically, you must do npm run webpack to get the result file updated

Am I missing something ?

**Comment by tettusud** [comment]
Hi I will check and update you

**Comment by tettusud** [comment]
Hi @aetna-softwares 
    I have published new version **merge-jsons-webpack-plugin@1.0.9**, can you try with this version . I have added code to handle json file changes.
 If you want some sample navigate  to /example folder in this repo and start the server and test it.

**Comment by aetna-softwares** [comment]
Hi,

It works with the "files" option but not with the "groupBy" / "pattern" option

**Comment by tettusud** [comment]
@aetna-softwares  , thanks for higlighting the issue , I have fixed it and published a new version **1.0.10**,please get the version and test

**Comment by aetna-softwares** [comment]
Hi,

I am sorry but I still have a case where it does not work, when I have many groupBy entries : 

`
              "groupBy":[
                            { "pattern":"./views/**/locales/en.json",
                               "fileName":"./locales/en.json"
                            },
                           { "pattern":"./views/**/locales/fr.json",
                               "fileName":"./locales/fr.json"
                            }
                        ]
`

When I have only 1 entry it works but with many entries it does not work anymore

**Comment by tettusud** [comment]
@Aetna-softwares
Can you check the example folder I have similar pattern where it works .Can you try it once and let me know if that is different from that of your scenerio.

**Comment by aetna-softwares** [comment]
yes, I did a simple project for testing, the problem is not the pattern but the fact that there is 2 object in the groupBy list.

**Comment by aetna-softwares** [comment]
Here, I give you my sample project : 
https://www.dropbox.com/s/drbiyase4scy741/testlang.zip?dl=0

**Comment by tettusud** [comment]
@aetna-softwares  in the examples i  have similar pattern like below, two objects inside ,anyway am trying to check your code meanwhile...

 "groupBy": [
          {
            "pattern": "{app/groupby/lang/en.json,app/groupby/lang/de.json}",
            "fileName": "jsons/languages.json"
          },
          {
            "pattern": "app/groupby/countries/*.json",
            "fileName": "jsons/countries.json"
          }

**Comment by tettusud** [comment]
I have copied your code and updated the example folder check here ,it works as expected
https://github.com/tettusud/merge-jsons-webpack-plugin/blob/master/example/webpack.config.js#L38

**Comment by aetna-softwares** [comment]
I updated the example and still have the problem.

Here is my test : 
run npm start
modify the file app/groupby/lang/view1/locales/en.json
the modification has no effect
while modify app/groupby/countries/usa.json
does work as expected

but it seems to be related to dev server mode because stopping and restarting the dev server does not apply the modification neither while running npm run build does generate correct output

**Comment by tettusud** [comment]
@aetna-softwares ,got it,let me see if I can resolve this...

**Comment by tettusud** [comment]
@aetna-softwares , apologies ,looks like some issue with the version i published earlier. It was not reflecting my changes, so I published a new version 1.0.11 again.Can you try with that.?
Thank you

**Comment by aetna-softwares** [comment]
Great! it's work as expected now

**Comment by aetna-softwares** [comment]
Hi,

Sorry to bother you again, I find an other case but I don't know if it can be handled easily.

Modification of a file matching the pattern works great but if I create a new file that matches the pattern it is not taken until I restart.

I think it is more difficult to wait for not existing files than modification in existing files so I would understand if you tell me it is impossible to do but it it is possible, it would be great to have it too !
